---
title: "Lab_3_4793_AGP"
author: "Austin Parker"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---




# Hint
$$Example \:\: 2.1$$

2 pics in markdown for (+) and (-) covariance for shiny to show theta goes thru zero

# Task 1

```{r setup}
library(Lab3)
getwd()
```

# Task 2

## Rotation in Matrix format

$$
\tilde {\textbf {X}}=\pmatrix{
cos(\theta) & sin(\theta)\\
-sin(\theta) & cos(\theta)\\
}\textbf X
$$

## Function

### $\tilde{x_1}, \tilde{x_2}$ Function

```{r , }
if(!require("mvtnorm")) install.packages("mvtnorm")

my.tilde=function(x1,x2,theta){ # x1,2 vectors, theta scalar
  x1t= x1*cos(theta) + x2*sin(theta)
  x2t=-x1*sin(theta) + x2*cos(theta)
  obj = list(x1t=x1t,x2t=x2t)
  return(obj)
}


set.seed(24) #  this will ensure everyone gets the same results
m=my.tilde(x1=rnorm(100),x2=rnorm(100),theta=pi/6)


# Xt <- as.data.frame(my.tilde(x1=rnorm(100),x2=rnorm(100),theta=pi/6))
#   # Xt; min(Xt[,1]); max(Xt[,1]); min(Xt[,2]); max(Xt[,2])
# 
# library(ggplot2)
# ggplot(Xt, aes(x1t, x2t)) + geom_point()
```


### $\tilde {\textbf {X}}$ Function
```{r , }
library(mvtnorm)
myxtilde = function(X,theta){
  cth = cos(theta)
  sth = sin(theta)
  mv = c(cth,-sth,sth,cth)
  Rt = matrix(mv,nr=2,nc=2, byrow=FALSE)
  Xt = Rt%*%t(X)
  t(Xt)
  #list(x1t = Xt[1,], x2t = Xt[2,])
}


varcov = matrix(c(100,100,100,400), nr=2,nc=2)
set.seed(24)

X = rmvnorm(100, mean=c(0,0), sigma=varcov)
Xt=myxtilde(X, 1.276795)
Xc=rbind(X,Xt)
n=dim(Xc)[1]
par(pty="s")

# make a scatter plot

plot(Xc[,1],Xc[,2], 
     col = rep(c("red", "blue"), 
               c(n/2,n/2)),
     asp=1,
     pch=19,
     xlab = "X1",
     ylab = "X2",
     main = paste("Rotation of ", 1.276795))
```





# Task 3

```{r}
# The function below is what we want to find the zero of
myfun=function(x) 300*sin(x)*cos(x) + 100*(cos(x)^2-sin(x)^2)

# The Newton-Raphson algorithm function
my.newt=function(x0,f=myfun,delta=0.0001,epsilon=1e-12){
  # x0 initial value
  #f the function to be zeroed
  #delta is the increment in the derivative
  #epsilon is how close our approximation is to zero
fdash=function(x) (f(x+delta)-f(x))/delta

d=x0 # initial values
i=0
x=c() # empty vector
y=c() # store y-values in a vector 
x[1]=x0 # assign initial guess
y[1]=f(x[1]) # initial y value
while(d > epsilon & i<100){ # ensures that it doesnt loop too much
  i=i+1 
  x[i+1]= x[i] - myfun(x[i])/fdash(x[i])# NR step
  y[i+1]=f(x[i+1]) # update y value
  d=abs((y[i]) - (y[i+1])) # update d
}
return(list(x=x, y=y, x.i = x[i], y.i = y[i]))
}

newt.raph = my.newt(x0 = 1, f = myfun)
newt.raph
```

## Correlation corresponding to $s_{ik}$, in other words $r_{ik}$

```{r}
library(Lab1)

varcov[1,2] / (sqrt(varcov[1,1]) * sqrt(varcov[2,2]))


```

# Roots from $(0, 2 \pi)$

```{r}

roots = vector(mode = "numeric", length = 4) 
roots <- c(1.255792, 2.833629, 4.411466, 5.970293)
roots

  root = vector(mode = "numeric", length = 4) 


newt.raph1 = my.newt(roots[1], f = myfun)
root[1] <- newt.raph1$x.i

newt.raph2 = my.newt(roots[2], f = myfun)
root[2] <- newt.raph2$x.i

newt.raph3 = my.newt(roots[3], f = myfun)
root[3] <- newt.raph3$x.i

newt.raph4 = my.newt(roots[4], f = myfun)
root[4] <- newt.raph4$x.i

root
```

## Plot $\tilde s_{12}$

```{r}
library(ggplot2)

ggplot(data = data.frame(x = c(0,2*pi)), aes(x)) +
  stat_function(fun = myfun, color = 'blue') +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  xlab("theta (in radians)") +
  ylab("f(theta)") +
  geom_text(x = root[1], y = 20, label = root[1]) +
  geom_text(x = root[2], y = 20, label = root[2]) +
  geom_text(x = root[3], y = 20, label = root[3]) +
  geom_text(x = root[4], y = 20, label = root[4])
```

# Task 4

```{r}
uniroot(f = myfun, interval = c(0, 2))
```


